name: test-windows-env

on:
  push:
  pull_request:

jobs:
  test-env-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          auto-update-conda: true
          python-version: "3.11"
          channels: conda-forge,defaults
          auto-activate-base: false

      - name: Create env from file
        shell: bash
        run: |
          conda env create -f lca_course_win64.yaml